### ISSUE TITLE
Duplicating project from SD to flash does not work

### ISSUE THREAD

**Issue by drasko** [nodesign/weio#104]
It creates new project on SD instead

**Comment by ks156** [comment]
1. Select an existing project in the example list.
2. Duplicate it on the SD card
3. Duplicate the project from the SD card to flash —> It doesn't work, and the project is created on the SD card
4. Try again, but in the popup, select "SD" and then "Flash" (just deselect "flash" and reselect it) —> It works

Conclusion : *storageUnit* seems not be correctly initialized somewhere.

**Comment by ks156** [comment]
Please confirm the fix and close if OK.
