### ISSUE TITLE
Strange behavior after flash weio_recovery and setting other name than weio

### ISSUE THREAD

**Issue by manuIO** [nodesign/weio#109]
After flash weio_recovery.bin and set other board name than weio an infinite loop asking for reload page appears.

To reproduce:
- flash weio_recovery.bin
- Do soft restart (after 505 internal server error)
- go to weio.local and set other board name than weio during sigin
- Then IDE is blocked loading and a message "I've lost connection" appears
- When you reload page the address is not founded

- Restart WeIO (disconnect-connect)
- Enter IDE address with your name (in my case manu.weio:8080)
- Then "I've lost connection" message appears, if you reload page the same message appears and that to the infinite.

**Comment by ks156** [comment]
I can't reproduce the bug. Someone can confirm it ?

but … at the signin page, when another name is set for the board, when the *Finish setup* button is clicked, the page simply reloads, meaning that the url (by default : weio.local) stays. If the *Bonjour* name is changed, the page should redirect to the correct URL.

**Comment by manuIO** [comment]
I can't reproduce any more after last update... maybe issue could be closed?
