### ISSUE TITLE
"create new project" item desappear in flash and sd directories

### ISSUE THREAD

**Issue by manuIO** [nodesign/weio#110]
When new project is created in flash or sd directories the item "create new project" disappears.

![screen shot 2015-01-27 at 18 14 15](https://cloud.githubusercontent.com/assets/9677805/5923072/eed92d96-a650-11e4-9575-91c208ab295d.png)
![screen shot 2015-01-27 at 18 14 45](https://cloud.githubusercontent.com/assets/9677805/5923076/f37d76d6-a650-11e4-9c98-60dd2195de30.png)

**Comment by nmarcetic** [comment]
This is a normal behavior. Create new project link is only present if don't have any projects on selected storage (to avoid empty menu and help you to create project faster).

Maybe we can change this, and always show "Create new project link" , but it is not planned to be so.

**Comment by manuIO** [comment]
Ok! I thought that you want to keep create "new project link" all the time.

**Comment by ukicar** [comment]
this is normal behavior it's a feature not bug... closing
