### ISSUE TITLE
Create projects in SD repertory without SD card

### ISSUE THREAD

**Issue by manuIO** [nodesign/weio#111]
Is possible to create projects in SD repertory without SD card, no warning message.

**Comment by drasko** [comment]
This is serious bug. Project is created directly on the flash under existing /weioUser/sd mountpoint. We must prevent this!

**Comment by ks156** [comment]
This issue should be fixed with the sd / usbFlash detection. https://github.com/nodesign/weio/pull/115

**Comment by drasko** [comment]
Manu,
can you please retest this?

**Comment by drasko** [comment]
Manu,
can you please test anc CLO if it is OK. This has been fixed by commits od uSD daemon and USB hotplug.

Might be still some errors in the app, so test is needed.

**Comment by manuIO** [comment]
Bug fixed!
