### ISSUE TITLE
attachInterrupt doesn't work on JS

### ISSUE THREAD

**Issue by manuIO** [nodesign/weio#127]
When the function is called with all parameters IDE console shows this error:
TypeError: attachInterrupt() takes exactly 4 parameters (2 given)

Here why:
https://github.com/nodesign/weio/blob/next/weioLib/weioParser.py#L163
https://github.com/nodesign/weio/blob/next/www/libs/weio/weioApi.js#L369

I've tried to fix the bug but I can't test it :
https://github.com/manuIO/weio/commit/86dafd2ab88880d37625b09e91f3b6a05df09a92

**Comment by ukicar** [comment]
why you can't test it? You need only one wire to do that. So you can contact it from 3.3V to some pin waiting pullup for example. I'll test it later

**Comment by drasko** [comment]
I think he is not in Paris, does not have a board with him...

**Comment by ukicar** [comment]
ok I'll correct this issue

**Comment by ks156** [comment]
Interrupts can be tested without wire.
Just attach an interrupt to a pin change the pin state with digitalWrite. It should work.

**Comment by ks156** [comment]
Fixed with this commit 6c310db6e5b4d713d9e8666e7610d43f5b8a6886, no ?
Can be closed ?

**Comment by manuIO** [comment]
yes!
