### ISSUE TITLE
IDE Examples can be deleted

### ISSUE THREAD

**Issue by manuIO** [nodesign/weio#134]
IDE Examples can be deleted while permissions are "read only"

**Comment by nmarcetic** [comment]
True , tnx @manuIO. Do you think we should disable this , or to leave a option to delete examples ? 
Maybe you will need free space and you don't want all examples any more. 
You can't edit those files , but maybe it's ok to leave the option to delete ?

**Comment by drasko** [comment]
Nope. Fix examples RO. If you want to free the space, you log onto the boards and you `rm -rf /weio/examples/*`

**Comment by manuIO** [comment]
@nmarcetic you're welcome!
I'm agree with Drasko.

**Comment by nmarcetic** [comment]
Should be fixed now!

**Comment by ks156** [comment]
I confirm the fix.

**Comment by ks156** [comment]
Unable to delete examples. Works fine. OK

**Comment by manuIO** [comment]
It works also for me! 
But I've noticed a minor bug: If you try to remove one "read only" file by clicking on the cross, then all project files are blocked and they can be openend
