### ISSUE TITLE
usbFlash cannot be opened using samba

### ISSUE THREAD

**Issue by manuIO** [nodesign/weio#135]
usbFlash repository cannot be opened using samba.
Error message (OSX): The folder “usbFlash” can’t be opened because you don’t have permission to see its contents.

**Comment by manuIO** [comment]
This bug seems fixed for me but I've noticed new bug with SD card and samba: https://github.com/nodesign/weio/issues/150

**Comment by manuIO** [comment]
can be closed

**Comment by ukicar** [comment]
ok thanks
