### ISSUE TITLE
samba permission of usbFlash and SD card bug after reboot

### ISSUE THREAD

**Issue by manuIO** [nodesign/weio#150]
To reproduce:
- Connect usbFlash / SD card, enable samba connection and see its content. 
- Reboot the board (disconnect and connect alim).
- Enable new samba connection and try to open usbFlash / SD card directory.

The result is the message: "The folder "usbFlash“ / "sd” can’t be opened because you don’t have permission to see its contents".

 I've noticed that removing generated __init__.py solve the problem until next connection.

 I've also noticed the same behavior when usbFlash / SD card is disconnected, samba connection restarted and usbFlash / SD card connected anew.

**Comment by ks156** [comment]
Fixed with this PR : https://github.com/nodesign/weio/pull/164
