### ISSUE TITLE
Empty field when duplicating projects causes error

### ISSUE THREAD

**Issue by ukicar** [nodesign/weio#151]
When duplicating project if only empty field is given WeIO calls root directory and this is bad. We need to isolate this case

**Comment by nmarcetic** [comment]
Can you pls describe "only empty field is given", empty filed for project name ?

**Comment by ukicar** [comment]
If you forget to give a name of project. No name provokes error

**Comment by nmarcetic** [comment]
Ok, all clear. I can do some validation, is that acceptable ?

**Comment by nmarcetic** [comment]
I mean on both side python and js validation.

**Comment by ukicar** [comment]
In the case of creating new project it's just rejected but no error message is shown. We can at least say with alert that field is empty

**Comment by nmarcetic** [comment]
Ok agree. I will make those changes.

**Comment by nmarcetic** [comment]
It's should be ok now, pull request sent.
