### ISSUE TITLE
pulseIn documentation is needed

### ISSUE THREAD

**Issue by ukicar** [nodesign/weio#162]
PulseIn documentation has never been written. We need for both Python and JS

**Comment by ks156** [comment]
Link #265 and https://github.com/nodesign/weioDoc/pull/16

**Comment by ks156** [comment]
@manuIO : Is it possible for you to test and write a js example and doc ?

**Comment by manuIO** [comment]
@ks156 yes of course! It's planned ;)

**Comment by ks156** [comment]
Thank you :stuck_out_tongue:

**Comment by manuIO** [comment]
js doc added: https://github.com/nodesign/weioDoc/pull/17

The issue can be closed

**Comment by ks156** [comment]
Thank you @manuIO !
