### ISSUE TITLE
Message stays "Warming up the engines..." upon start

### ISSUE THREAD

**Issue by drasko** [nodesign/weio#169]
Upon start thi is written in the header:
weio.local on 192.168.0.25
Warming up the engines...

This sentence should be corrected, and we have an impression that something should happen (this is an old message from the time when userTornad start was slow).

**Comment by ukicar** [comment]
Yes good point! Corrected in this commit : https://github.com/nodesign/weio/commit/dc09ac2d0abf2795c72ae7ceef23ced418a25cc0

**Comment by drasko** [comment]
I am not sure that this commit resolves the issue. I did not even see "WeIO is ready!". All I saw is "Warming up the engines.." and it is stucked there.

I will reopen the issue, but if you tested and it is OK for you, then please close it.

**Comment by ukicar** [comment]
it resolves it's my error. I turned first warming up.. to "weio ready" and I committed by error then I changed to "weio running". I tested it's OK
