### ISSUE TITLE
Ace v1.1.9 displays errors on python code

### ISSUE THREAD

**Issue by ks156** [nodesign/weio#185]
With the new version of ACE, when a new project is created and main.py is shown, there's two errors pointed by the editors. One for the import, another for setup function.
If the file is closed and then re-opened, the errors disappear.

![image](https://cloud.githubusercontent.com/assets/55508/7216969/e9eaa208-e613-11e4-96df-3eddf5058793.png)

**Comment by nmarcetic** [comment]
@ks156 I can't reproduce this bug, using chrome and firefox (i think its not related to browser). I try with new project main.py and creating new files also no error's.

**Comment by ukicar** [comment]
Can't reproduce neither. Tested on safari

**Comment by nmarcetic** [comment]
@ks156 Try to hover the error , so we can see what Ace is telling about those errors (i notice this in lot of IDE's).

**Comment by ks156** [comment]
I'll retest tonight if I find some time

**Comment by ks156** [comment]
I can't reproduce this bug anymore... cache ?

**Comment by nmarcetic** [comment]
Its possible. As @ukicar says Ace is very crazy with cache :)
