### ISSUE TITLE
Autosave message override the "WeIO is running" message

### ISSUE THREAD

**Issue by ks156** [nodesign/weio#186]
When a file is open in the IDE and the project is started, the autosave feature override the message "WeIO is running'" on the top bar.

![image](https://cloud.githubusercontent.com/assets/55508/7217006/06e00f8c-e615-11e4-84d0-2aabe0ddea7c.png)

**Comment by ukicar** [comment]
This is not a bug. You can still edit files while something is running. It's crucial to inform user that some file is saved. Maybe we can add some delay in "index.html saved" message so it can be gone after 5 seconds.

**Comment by ks156** [comment]
Ok. If this behavior is OK for you, then close this issue
