### ISSUE TITLE
Deleting files broken!

### ISSUE THREAD

**Issue by ukicar** [nodesign/weio#188]
Since last updates we can't delete files inside interface. We can't delete files nor projects. Something is broken

**Comment by ks156** [comment]
Uros, related to #134 ?

**Comment by ukicar** [comment]
No, not related. User files and projects can't be deleted now

**Comment by nmarcetic** [comment]
I will take a look later  whats happening... I work on this last night.

**Comment by nmarcetic** [comment]
Should be fixed now, my mistake , sry!

**Comment by ks156** [comment]
Confirmed. OK
