### ISSUE TITLE
Board SVG image in the "Board" section of IDE has wrong PWM pins

### ISSUE THREAD

**Issue by drasko** [nodesign/weio#193]
Image shows tthat pins 19, 20 and 21 are RGB, when it should be 18, 19 and 20.

This is very confusing for the Blinky example.

![screenshot from 2015-04-19 19 44 23](https://cloud.githubusercontent.com/assets/149944/7220564/a508b1e8-e6cc-11e4-9d04-6401ac2034c6.png)

**Comment by ukicar** [comment]
corrected
