### ISSUE TITLE
root directory is not writable over Samba

### ISSUE THREAD

**Issue by manuIO** [nodesign/weio#195]
When I try to save files in root (/weio) over Samba I get this error message: open("/Volumes/root/__init__.py~"): Permission denied

**Comment by manuIO** [comment]
fixed here: https://github.com/nodesign/weio/pull/196
@ks156 it's a good solution or this will break something?

**Comment by ks156** [comment]
Ow, yes, we didn't saw this one. Thank you.

**Comment by manuIO** [comment]
can be closed?

**Comment by ks156** [comment]
Permissions are OK now. Fixed
