### ISSUE TITLE
Fritzing schematic for blink_PY is not correct

### ISSUE THREAD

**Issue by ks156** [nodesign/weio#198]
The fritzing schematic for blink_PY example is not correct : 
http://we-io.net/doc/examples.html#blink-py

A strap between F17 and E17 must be added (or move C17 to F17), otherwise the GND is not connected.
In addition, I would suggest lower resistors value. For example, 180R or even 150R.

**Comment by manuIO** [comment]
It's because we-io.net/doc is not up to date, here is good schematic : https://github.com/nodesign/weioDoc/blob/master/images/blink_PY.png
@ukicar @drasko why web site documentation is not automatically updated with https://github.com/nodesign/weioDoc/ ?

**Comment by drasko** [comment]
@ukicar can you take care of this?

**Comment by ks156** [comment]
The doc is now correctly updated. Schematic is OK.
