### ISSUE TITLE
Create or duplicate projects with existent name project

### ISSUE THREAD

**Issue by manuIO** [nodesign/weio#199]
Duplicate or create a new project with a name that already exist in the flash makes that no warning message is displayed (in the case of duplicate project a message appears but is a wrong message: "connection lost...") and the project is not created.

**Comment by nmarcetic** [comment]
@manuIO Tnx for info.
I know for this, its not a bug , but its not a perfect behavior.  What should be the scenario, what do you propose ? 
@ukicar can you please participate with your opinion.

**Comment by ukicar** [comment]
In this case we have to launch one modal view with warning. This project name already exists, please choose another one

**Comment by nmarcetic** [comment]
Ok, tnx. @manuIO if you agree we will add modal dialog warning.

**Comment by ukicar** [comment]
I'm ok with modal warning

**Comment by drasko** [comment]
Go with modal.

**Comment by manuIO** [comment]
:+1:

**Comment by nmarcetic** [comment]
Its should be ok now, i added msg on dialog box, we already handle empty project name like this. Please test, i have some conflicts with dasboard.js file.

**Comment by manuIO** [comment]
can be closed?

**Comment by ks156** [comment]
When I create a new project with an already existing name, nothing happens. No messages at all.
When I duplicate a project with an existing name, the message "I've lost connection!" appears.

Not fixed for me.
