### ISSUE TITLE
Default debounce time for interrupt is too short

### ISSUE THREAD

**Issue by ks156** [nodesign/weio#204]
The default debounce delay for interrupts is fixed at 50us. This is usually too short for most applications (encoder, switches, and basically UI devices).
This default delay should be increased at, say, 10ms. This will improve the user experience for users who don't know much the hardware. In addition, this parameter must be well explained in the documentation and the default delay must be explicitly indicated.

**Comment by ks156** [comment]
@ukicar : 10ms, OK for you ?

**Comment by ukicar** [comment]
Ok for me

**Comment by ks156** [comment]
I made a mistake. Default debounce time is 50**ms**, not 50**us**.

**Comment by drasko** [comment]
OK for me.
