### ISSUE TITLE
Preview not displayed if clicked before PLAY

### ISSUE THREAD

**Issue by drasko** [nodesign/weio#215]
Preview is supposed to trigger PLAY, however it comes too late.

This provokes error in displaying the page:
![screenshot from 2015-05-02 21 28 11](https://cloud.githubusercontent.com/assets/149944/7442471/3a6ef1fc-f113-11e4-85e7-4d9de7438652.png)

Insert a check not to load the iFrame before it is not served, or to re-load it somehow.

**Comment by drasko** [comment]
@nmarcetic it would be great to have fix for this bug for v1.1. Do you think it is possible to take this one urgently?

**Comment by nmarcetic** [comment]
Yes, i will take a look tonight.

**Comment by ks156** [comment]
Clicking on *PREVIEW* when project is stopped automatically start the project, and display it.
OK for me.

**Comment by manuIO** [comment]
Confirmed :+1:
