### ISSUE TITLE
Updater - root user password not preserved

### ISSUE THREAD

**Issue by drasko** [nodesign/weio#222]
Sysupgrade should preserve user passwords. However, due to the known bug in OpenWRT: https://dev.openwrt.org/ticket/18206, UNIX account passwords are not preserved.

`root` in WeIO thus uses password after the sysupgrade, and `ssh` and `samba` are not accessible.

Proposed workaround is on the bug report: _To prevent that, you need to edit /etc/keep.d/base-files-essentials to include also "/etc/shadow"._

This should be kept until we port WeIO to OpenWRT mainstream, and we pass to more modern OpenWRT version.

**Comment by ks156** [comment]
@drasko : you put it in the 1.2, but it seems to be fixed by ad5a254fcf71eb0f84aeb198b38f8e47657190e1. The code for 1.1 is already frozen ?

**Comment by drasko** [comment]
@ks156 sorry, corrected to v1.1.

**Comment by ks156** [comment]
Tested, and password preserved.
