### ISSUE TITLE
powerModule.py not working

### ISSUE THREAD

**Issue by bltzr** [nodesign/weio#233]
Hi there !

I'm trying to use the powerModule
as @ks156 told me on may 1st on gitter, 
I have added 'from weioLib.weio import *' inside of /weio/things/output/power/powerModule.py, 
then restarted
but that didn't help
I still get these errors
https://gist.github.com/anonymous/7d31996c9cdc11f87a43

anybody having a hint at that ?

**Comment by ks156** [comment]
There's a missing import somewhere. I'll check it ASAP.
Can you also attach your code ? It will be easier to test.
Thanks
Paul

**Comment by bltzr** [comment]
Thanks, Paul
I don't have any specific code, I'm using the powerModule example

**Comment by ks156** [comment]
Adding
````
from weioLib.weioSPI import SPILib
````
just after
````
from weioLib.weio import *
````
on
````
/weio/things/output/power/powerModule.py
````
should fix the problem. Can you confirm ?

**Comment by bltzr** [comment]
right, I don’t have any errors any more !!

now, I need to figure out how to use them, but that's another issue

**Comment by bltzr** [comment]
big thanks !!

**Comment by ks156** [comment]
Glad to know it works now.
