### ISSUE TITLE
WeIO rescue configuration not updated after passing to v1.1

### ISSUE THREAD

**Issue by ukicar** [nodesign/weio#236]
As these files are marked against erasing. https://github.com/nodesign/weio/blob/v1.1/openWrt/files/lib/upgrade/keep.d/base-files#L3
New parameters are never updated with classical update procedure.

The parameter in question is this one 
https://github.com/nodesign/weio/blob/v1.1/openWrt/files/etc/config/wireless.ap.rescue#L3

This is possible to correct with migrateConfig.py https://github.com/nodesign/weio/blob/master/scripts/migrateConfig.py

that needs to extend it's action from config.weio to some other files in os that needs to be updated

**Comment by drasko** [comment]
Who is working on this? @nmarcetic? @ukicar?

**Comment by ks156** [comment]
Is it fixed with the new updater ? I didn't check ..

**Comment by ukicar** [comment]
Yes this has been repaired and tested
