### ISSUE TITLE
Pins 8-12 not usable for digital io

### ISSUE THREAD

**Issue by AlexDus** [nodesign/weio#240]
When i try to use port 8-12 for digital io it just does not work. I am using the python commands digitalRead and digitalWrite. Ports 7 and 13 work without any problems using the same code. I have two weio boards and both behave the same. I am using firmware version 1.1

**Comment by ukicar** [comment]
Hello Alex,
I just tested on one WeIO board and I can't reproduce your bug. I used this code for testing purpose 
'''python
from weioLib.weio import *
pin = 12
def setup():
    attach.process(myProcess)
    
def myProcess():
    while True :
        digitalWrite(pin,HIGH)
        delay(70)
        digitalWrite(pin,LOW)
        delay(70)
        
'''
Please can you try with this code and report us your findings. We will try to help you resolve this issue

**Comment by AlexDus** [comment]
Hi,

that's almost the same code i used to test the problem. Still the same result. Tried it with pin 7 and 8. Pin 7 is working, pin 8 is not. Even made a firmware recovery on one of the boards a couple a minutes ago - did not help. By the way - that's the way i installed 1.1 on both of the boards. I didn't use the online update. Maybe something in the weio_recovery.bin?

**Comment by drasko** [comment]
Hi Alex,
just a quick question - did you saw the same behavior with version 1.0?

I am trying to understand if the error comes from SW, or is it some HW
issue with your board.

BR,
Drasko

**Comment by AlexDus** [comment]
Hi Drasko,

just downgraded one board to 1.0. The version shows the same behavior. Points to a HW problem in both boards.

Regards,
Alex

**Comment by drasko** [comment]
Hi Alex,

On Jun 7, 2015 2:29 PM, "AlexDus" <notifications@github.com> wrote:
>
> Hi Drasko,
>
> just downgraded one board to 1.0. The version shows the same behavior.
Points to a HW problem in both boards.

Thanks for checking this out.

Let's wait a bit what what other guys looking this list might suggest, but
it is very possible that some connectors were badly soldered on your board.

In the meantime I will check with 8Devices, and you will probably have to
send them your board for replacement.

I am very sorry for this, we had no problems of this kind reported so far,
but I guess that some errors might slipped through.

We will refund all the postal costs.

Best regards
Drasko

**Comment by AlexDus** [comment]
Thanks for your quick support.

Regards
Alex

**Comment by AlexDus** [comment]
Hi Drasko,

anything new regarding the problem?

Regards
Alex

**Comment by drasko** [comment]
@ukicar what is the status on this? Can you please explain the issues reported by 8Devices? What are the actions to take?

**Comment by ks156** [comment]
I'll check it.

**Comment by ks156** [comment]
The pinout of pins 8-14 have changed. Problem is that for those (I don't know who nor how many boards are concerned), the new pin layout will not be compatible. 
Anyway, the new layout is applicable both for board produced at the beginning of this year (tested with my board), and new batch coming. So this change makes sense. 
I can keep the old config as a separate file, for compatibility. What do you think ?

**Comment by drasko** [comment]
No need IMHO. This comments will be used as a doc, and whoever runs into she problem should shout here or in the forum.

Can we paste this old config and instructions somewhere, for the documentation sake?

**Comment by ks156** [comment]
Ok, I'll write something on the wiki and apply the new pinout in IoTPy

**Comment by ks156** [comment]
> No need IMHO

I've kept the old config in the same file, with another name (WEIO_PINOUT_OLD). It would be easier to switch to that config if needed
