### ISSUE TITLE
Documentation page should reflect weioDoc

### ISSUE THREAD

**Issue by drasko** [nodesign/weio#246]
Flatdoc (http://ricostacruz.com/flatdoc/) has a feature to reflect GitHub repo, and automatically render tha page from a code in the repo.

Currently this is not the case, and document page http://we-io.net/doc/gettingStarted.html has to be manually update each time via FTP.

Please enable this automatic renender feature - so that we can just push to GitHub and forget.

**Comment by ukicar** [comment]
Done! Tested
