### ISSUE TITLE
Closing AND Deleting Files not possible (V1.2)

### ISSUE THREAD

**Issue by ementi** [nodesign/weio#259]
Deleting files (Clicking "X" on the left side of the File-Tree) isn't possible anymore since update to V1.2
There is no "X" anymore in the top right corner, to close open pages i.e. main.py

**Comment by ks156** [comment]
I confirm : click "X" on the file tree doesn't have any effect.

**Comment by ks156** [comment]
Bug introduced in this commit : https://github.com/nodesign/weio/commit/a9ce0f26106eb6546a8c87c9d188c252b3abe231

**Comment by ks156** [comment]
Fixed by PR #263
