### ISSUE TITLE
Filename truncated on FAT SD card and usb flash

### ISSUE THREAD

**Issue by ks156** [nodesign/weio#261]
In some case (depending on the way the removable device is formatted), SD cards and USB Flash drives are not usable.
This is due to some missing native langage modules in the kernel.

(ref @jsiobj / http://we-io.net/forum/viewtopic.php?f=2&t=775)

**Comment by jsiobj** [comment]
@ks156 : Just tried the image provided in #258 and now SD and USB are properly mounted as vfat :-)
```
/dev/sda1 on /weioUser/sd type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
```
Thanks !

**Comment by ks156** [comment]
Thank you for this confirmation @jsiobj !

**Comment by ks156** [comment]
Merged and will be added on v1.3

**Comment by ementi** [comment]
So with the new weio_recovery.bin Paul sent me, my SD Card works now perfectly fine. I have access to the Python files and to the html files with longer names too. 
Thank you for your support.

**Comment by ks156** [comment]
@ementi : Thanks for your feedback !
