### ISSUE TITLE
usb/sd cards detected as /dev/sda 

### ISSUE THREAD

**Issue by ondonadas** [nodesign/weio#269]
Hi @drasko 

Fyi:

I've been using weio sd/usb memory card detection. After some days I've noticed that there usb drives and microsd cards that are detected as /dev/sda (please note the lack of partition number). In other words the drive is never mounted. In order to avoid this I've modified /etc/hotplug.d/weio/10-weio-removable-devices:

<pre>
[ -e $sd/`basename $sd`1 ] && sd_name=`basename $sd`1 || sd_name=`basename $sd`
</pre>

Please note that sysfs shows /sys/bus/scsi/drivers/sd/0\:0\:0\:0/block/sda/sda1 file instead of /sys/bus/scsi/drivers/sd/0\:0\:0\:0/block/sda1

sergio

**Comment by drasko** [comment]
@ondonadas  very strange... Is this card formatted correctly? Looks like it's partition table is bogus.

**Comment by ondonadas** [comment]
Yes, the card is formatted right. Ubuntu shows FAT32 format

**Comment by ks156** [comment]
@ondonadas, if I understand correctly, your SD cards or USB drives were mounted without any problem before, and now are not mounted at all ?

It looks like the partition table is not correct. Ubuntu shows /dev/sd**x****y**, or only /dev/sd**x** ?

**Comment by ondonadas** [comment]
Paul, some of them are correctly detected. Others didn't.

Let me try to format them with different OS. Let see what happens...
El dia 18/11/2015 19:29, "Paul RATHGEB" <notifications@github.com> va
escriure:

**Comment by ks156** [comment]
> Paul, some of them are correctly detected. Others didn't.

They're correctly detected on WeIO, or on Ubuntu ? Are the partition scheme consistent between Ubuntu and WeIO ? (I mean, does a card that doesn't have a partition number on WeIO has one on Ubuntu ?)
