### ISSUE TITLE
unable to start AP

### ISSUE THREAD

**Issue by Capt-Cpt** [nodesign/weio#274]
Brand new WEIO board does not behave as described at start-up : when powered-up (via USB cable), power led lights up, both AP & STA led blinks 3 or 4 times, eventually AP led becomes steady green but glowing very low. Board adress never shows in available network list...

**Comment by manuIO** [comment]
Hi @Capt-Cpt,

I've already noticed this bug after some updates. You can probably fix the issue if you reinstall the FW as explained here:
https://github.com/nodesign/weio/wiki/WeIO-Recovery#offline-manual-update-via-sd-card-or-usb-key

**Comment by Capt-Cpt** [comment]
Hi @manuIO,

Thank you for your reply. I have already tried that procedure as described in the WEIO-Recovery page : 
*" Plug SD card / USBkey to WeIO
Press and hold SOFT RESET button on WeIO
Plug power to WeIO while keeping the SOFT RESET button pressed
You will see STA led blink 3 times
Now you can release the SOFT RESET BUTTON "*
Trouble is that I never reach the step where *"STA led __blinks 3 times__"*.
I see from page http://we-io.net/forum/viewtopic.php?f=2&t=741 that I am not the only one. 
Looking forward what I can find to help in that topic... And will have a try with SSH (according to @drasko), if it works...

**Comment by manuIO** [comment]
HI @Capt-Cpt ,

I've already bypassed this issue, is tedious I know, but is not impossible. You need to try several times.
Please can you try to things:
- Copy the weio_recovery.bin using an empty SD card or USBKey (if you have not already done).
- Copy the weio_recovery.bin but removing the .bin extension

**Comment by Capt-Cpt** [comment]
Hi @manuIO 

Don't know how it worked, but eventually I got normal start without having to flash FW. You were right, I hat to try several times... Seems that powering board with 5 DC power worked better thant by USB cable.
I can now experiment with my board...

Thanks a lot for help

**Comment by drasko** [comment]
\o/

**Comment by manuIO** [comment]
:+1: 

You're welcome @Capt-Cpt !
