### ISSUE TITLE
IDE - Hight problem on preview display

### ISSUE THREAD

**Issue by manuIO** [nodesign/weio#43]
Hight is not totaly visible on preview display.
Test example digitalWriteColorsLed_JS.

**Comment by manuIO** [comment]
fixed here:
https://github.com/manuIO/weio/commit/339875062ed6c0d3d9c40722e0133a0fab4aa007

**Comment by drasko** [comment]
Closing. Thanks @manuIO!

**Comment by manuIO** [comment]
:+1:
