### ISSUE TITLE
Fast click from "stop" to "play" will break

### ISSUE THREAD

**Issue by ukicar** [nodesign/weio#50]
If clicked from "stop" to "play" rapidely program will break. This occurs really often. That's because WeIO don't have enough time to reset LPC co-processor. When stop is clicked, reset pin on LPC is activated and LPC goes to coma. OS needs little bit less than two seconds to enumerate again co-processor and open protocol. The question is how to solve this issue?

the simplest thing but not the most elegant is to add a delay of 2sec before activating play after stop....

**Comment by ks156** [comment]
First issue (PLAY / STOP / PLAY) is fixed, but indeed, double click on the play button cause weird behavior (LPC coprocesseur is not present or tornado crash).

**Comment by drasko** [comment]
Uros or Nikola, please disable in the front-end JS PLAY and STOP buttons once they have been clicked for a certain delay - every clikc manipulates with LPC behind and this takes time!

**Comment by nmarcetic** [comment]
I send you pull request, please test it if you can. I am busy at the moment, no time for testing sorry, but it should work :) .

**Comment by nmarcetic** [comment]
Please close this one.
