### ISSUE TITLE
Give some Internet service examples like twitter, fb or other

### ISSUE THREAD

**Issue by ukicar** [nodesign/weio#53]
It will be really nice to have some Twitter or FB examples in our menu. Something really simple like turn the LED ON when someone twitt my name or similar. These examples will show that we are internet services ready. If it comes to install some Python libraries to have some specific support just let me know, so we can discuss embedding them directly in fw.

**Comment by ks156** [comment]
@manuIO added these examples (for v1.0) : 
- facebook
- gmail
- twitter

Do we need more (yeap, probably, but from the community :smile:)? Does this issue still have sense ?
