### ISSUE TITLE
IDE - Long lines on console

### ISSUE THREAD

**Issue by manuIO** [nodesign/weio#55]
Console don't have automatically new line return, all entries are diplayed in one line.
To test it print long entry.

**Comment by manuIO** [comment]
Fixed in this commit:
https://github.com/manuIO/weio/commit/9eb4475e47f6858255d64d80ccf4a7d9d6852bc7

After:
![screen shot 2015-03-05 at 00 27 02](https://cloud.githubusercontent.com/assets/9677805/6496055/8a392f30-c2cf-11e4-8e5e-20882212d9dc.png)
![screen shot 2015-03-05 at 00 26 45](https://cloud.githubusercontent.com/assets/9677805/6496059/949a5b16-c2cf-11e4-8027-c65b2f09b029.png)

Now:
![screen shot 2015-03-05 at 00 29 34](https://cloud.githubusercontent.com/assets/9677805/6496062/985c3f62-c2cf-11e4-98fc-251a553d78dd.png)

**Comment by manuIO** [comment]
can be closed?

**Comment by ukicar** [comment]
thanks!!

**Comment by ukicar** [comment]
thanks
