### ISSUE TITLE
Not allowed to write using samba

### ISSUE THREAD

**Issue by manuIO** [nodesign/weio#60]
Today I have flash weio_recovery.bin to start with a new card. I have done the first login using "weio" as login and "weio" as password. Then after update I tried to write using samba but no way to do it, I can only read. Somebody know why?

**Comment by drasko** [comment]
Fixed by correct /etc/config/samba conf

**Comment by manuIO** [comment]
can be closed!

**Comment by ks156** [comment]
Fixed by this PR : https://github.com/nodesign/weio/pull/164
