### ISSUE TITLE
bgColorLEDWeb example don't work

### ISSUE THREAD

**Issue by manuIO** [nodesign/weio#63]
bgColorLEDWeb example don't work for me, I've errors with setColor function: https://github.com/nodesign/weio/blob/next/examples/bgColorLEDWEB/main.py#L33

**Comment by ks156** [comment]
If someone can (briefly) explain how to call a java fonction from python, I'll fix this example quickly.

**Comment by drasko** [comment]
Whoops... Not possible I think. This feature is missing now - we broke a lot of stuff.

I will take a look tonight at two things:

1) Shared variables between processes (https://docs.python.org/2/library/multiprocessing.html#sharing-state-between-processes), I think dict and Manager can do the job

2) Py -> JS (not difficult, but demands some work)

**Comment by ks156** [comment]
Ok, so for the first release, it's maybe better to remove this example ?
Same for webCamSinglePhotoWEB I guess. (https://github.com/nodesign/weio/blob/next/examples/webService/webCamSinglePhotoWEB/main.py#L29-L30)

**Comment by manuIO** [comment]
I think so!

**Comment by ks156** [comment]
Can be closed ! https://github.com/nodesign/weio/commit/7920773e4283107f6529f62ba077ebc1b7c6f68e

**Comment by manuIO** [comment]
good job!
