### ISSUE TITLE
IDE -  Only digital examples have scroll menu

### ISSUE THREAD

**Issue by manuIO** [nodesign/weio#74]
In new examples structure only digital examples have scroll menu, 
Also some examples can't be opened because of heigth (for example sensors).

**Comment by manuIO** [comment]
In fact is because there are more than 10 examples in digital (I can see that when I zoom out but not with normal display). The bug is because of height of examples dropdown-menu when is unrolled.

To test change the browser zoom.

**Comment by manuIO** [comment]
![screen shot 2015-01-04 at 20 24 50](https://cloud.githubusercontent.com/assets/9677805/5607200/23d0be5e-9451-11e4-94ca-994c2b120a19.png)

**Comment by manuIO** [comment]
Fixed in this commit https://github.com/manuIO/weio/commit/e7c5da5370df481f7969cce6cb11e92f14562c75

![screen shot 2015-01-04 at 20 35 19](https://cloud.githubusercontent.com/assets/9677805/5607206/69fcb1d0-9451-11e4-86d0-3acfd8b5ce75.png)

**Comment by manuIO** [comment]
Issue can be closed?

**Comment by drasko** [comment]
@nmarcetic confirmed it can. Closing.
