### ISSUE TITLE
IDE- Missing digital and analog examples

### ISSUE THREAD

**Issue by manuIO** [nodesign/weio#77]
Some examples are missing in digital (pwmWrite, digitalWriteColorsLed, etc...) and analog (analogRead_JS and analogRead_PY)

**Comment by manuIO** [comment]
Duplicated issue.
The bug is because of height of examples dropdown-menu when is unrolled.

**Comment by manuIO** [comment]
Issue can be closed?

**Comment by ukicar** [comment]
Yes!
