### ISSUE TITLE
Project files tree enable files reopening  

### ISSUE THREAD

**Issue by nmarcetic** [nodesign/weio#94]
If the file is already opened, click on that file in project files tree will not reopen file.
TODO: Implement this feature.

**Comment by ks156** [comment]
https://github.com/nmarcetic/weio/commit/f33abdf00d535e2c9099d698a6b9b7695b72749a

I confirm the fix

**Comment by ks156** [comment]
Duplicated with #152

**Comment by ks156** [comment]
Tested. OK

**Comment by manuIO** [comment]
Confirmed :+1:
