### ISSUE TITLE
Date and time are not correct

### ISSUE THREAD

**Issue by ukicar** [nodesign/weio#98]
We are using NTPD to sync with atomic clocks over Internet. Once WeIO is connected to the Internet it has to show correct time. There is some problem with NTPD configuration, maybe distant servers are never reachable?

**Comment by nmarcetic** [comment]
I will fix this tonight.

**Comment by drasko** [comment]
@nmarcetic please use new binary, I added missing `ntpdate`. Tell us if everything is OK, point is that you do not have to use opkg install and that we have ntp functional by default.

**Comment by nmarcetic** [comment]
Ok

**Comment by nmarcetic** [comment]
Please try to set timezone in IDE settings page. Its should be ok now.
