### ISSUE TITLE
Can not create directories with Samba

### ISSUE THREAD

**Issue by drasko** [nodesign/weio#99]
I tried creating a dir somewhere in WeIO via Samba, and this is not possible.

This might be useful for the users to group their files.

Samba server permissions need to be checked.

**Comment by manuIO** [comment]
It's because "others" don't have permissions. I changed directory mask by 707 (https://github.com/manuIO/weio/commit/300b060b20bebb5e721437ee9fc7be16153147b6). 
I also tried 706 mask but It doesn't work...

**Comment by drasko** [comment]
This was not well done, and I had to correct it - see my commits: https://github.com/nodesign/weio/commit/e15d9dae753e723d8b0494ce4bd86fc54a449936 and https://github.com/nodesign/weio/commit/a1e9c01827076835b7d4cf327c287b6216b1576e.

Thing is that **only** /etc/config/samba should be changed, without touching /etc/samba/smb.conf, which is just a symlink to /var/etc/smb.conf, which itself is auto-generated from /etc/samba/smb.conf.template with each reastart of samba server.

Either change template, or /etc/config/samba, with later recommended.
